print(f"One day, I decided to visit the zoo. As soon as I walked in, I saw an ANIMAL. It looked very ADJECTIVE and was making a lot of NOUN. I quickly walked over to see the ANIMAL, which was VERB in its cage. I quickly decided to VERB2 and then go check out the ANIMAL2 cage. He was very ADJECTIVE2 and was VERB3 a lot. I had a VERB4 time at the zoo!")
print("Insert your own words in the placeholders above to create your own madlib!")

animal = input("Enter the first animal: ")
adjective = input("Enter the adjective: ")
noun = input("Enter the noun: ")
verb = input("Enter the verb: ")
verb2 = input("Enter the second verb: ")
animal2 = input("Enter the second animal: ")
adjective2 = input("Enter the second adjective: ")
verb3 = input("Enter the third verb: ")
verb4 = input("Enter the fourth verb: ")
print(f"One day, I decided to visit the zoo. As soon as I walked in, I saw an {animal}. It looked very {adjective} and was making a lot of {noun}. I quickly walked over to see the {animal}, which was {verb} in its cage. I quickly decided to {verb2} and then go check out the {animal2} cage. He was very {adjective2} and was {verb3} a lot. I had a {verb4} time at the zoo!")